version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "${DJANGO_BIND_PORT}:${DJANGO_BIND_PORT}"
    command: [ "./scripts/start-local-enviroment.sh" ]
